### ISSUE TITLE
Enable distrib of tools with docker

### ISSUE THREAD

**Issue by bwnyasse** [rushio-consulting/coverage_service#1]

**Comment by bwnyasse** [comment]
Hi @kleak , 

j'ai une erreur quand je lance le container : 
Je suis sur un vps linux

Et il a pris un sacré temps sur le `pub get`
```
bwnyasse at vps311007 in gr/rushio-consulting/coverage_service on  master [!] on 🐳 v18.09.5
•% ➜ docker run --rm -v $PWD:/coverage-project rushioconsulting/coverage_service
[INFO] : Server listening on port 40000
[FINE] CoverageService: id is 46f2acd9-7bc2-468c-bf9e-a34952e55975
[INFO] CoverageService: start coverage
[INFO] CoverageService: extract from zip
[INFO] CoverageService: end extract from zip
[FINE] CoverageService: get project name
[FINE] CoverageService.coverage_service: Check if it's Flutter
[FINE] CoverageService.coverage_service: Dart project
[INFO] CoverageService.coverage_service: pub get
[INFO] CoverageService.coverage_service: get observatory uri
[INFO] CoverageService.coverage_service: collect_coverage
[SEVERE] CoverageService.coverage_service: ProcessException: No such file or directory
  Command: collect_coverage --uri=http://127.0.0.1:43295/txIbkbxxmG0=/ --out=coverage/coverage.json --wait-paused --resume-isolates
Unhandled exception:
gRPC Error (13, FAIL_LAUNCH_OBSERVATORY)
#0      Cli.getCoverage (package:coverage_service/src/cli/cli.dart:38:22)
<asynchronous suspension>
#1      main (file:///service/bin/main.dart:28:30)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
mv: cannot stat '/tmp/rushio-gen-coverage-46f2acd9-7bc2-468c-bf9e-a34952e55975/coverage': No such file or directory
Failed to start the coverage generation: 1
```

**Comment by bwnyasse** [comment]
@kleak voila le [launcher](https://github.com/rushio-consulting/coverage_service/blob/master/launch.sh) , je démarre le serveur en background

**Comment by bwnyasse** [comment]
Available in master branch
